# Customize to your needs...
export PATH=/Users/petersen/.rbenv/shims:/Users/petersen/.rbenv/bin:/usr/local/bin:/usr/local/sbin:$HOME/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/local/mysql/bin
